import os
from dotenv import load_dotenv

load_dotenv()

SERPER_API_KEY = os.getenv("SERPER_API_KEY")
APIFY_API_TOKEN = os.getenv("APIFY_API_TOKEN")

# Apify actor IDs for enrichment phases
APIFY_ACTOR_GOOGLE_REVIEWS = "compass/google-maps-reviews-scraper"
APIFY_ACTOR_IG_REELS = "apify/instagram-reel-scraper"
APIFY_ACTOR_IG_POSTS = "apify/instagram-post-scraper"
APIFY_ACTOR_OPENTABLE = "shahidirfan/opentable-scraper"

# Resy API config (reverse-engineered, may be fragile)
RESY_API_BASE = "https://api.resy.com/4"
RESY_API_KEY = os.getenv("RESY_API_KEY", "")

# Search queries by business type
SEARCH_QUERIES = {
    "restaurant_destination": [
        "best restaurant",
        "fine dining",
        "tasting menu restaurant",
        "michelin star restaurant",
        "michelin recommended restaurant",
        "james beard award restaurant",
        "hard to book restaurant",
        "sought after restaurant",
        "eater restaurant",
        "chef driven restaurant",
        "omakase restaurant",
        "prix fixe restaurant",
    ],
    "restaurant_neighborhood": [
        "popular restaurant",
        "farm to table restaurant",
        "neighborhood favorite restaurant",
        "best new restaurant",
        "local favorite restaurant",
        "hidden gem restaurant",
        "best brunch spot",
        "best date night restaurant",
        "best pasta restaurant",
        "best seafood restaurant",
        "best steakhouse",
        "best pizza restaurant",
    ],
    "butcher_premium": [
        "best butcher shop",
        "artisan butcher shop",
        "craft butcher",
        "whole animal butcher",
        "dry aged beef butcher",
        "heritage breed butcher",
        "wagyu butcher",
        "prime meat shop",
        "gourmet butcher shop",
        "nose to tail butcher",
        "sustainable butcher shop",
        "organic butcher shop",
        "pasture raised meat shop",
        "grass fed butcher",
        "farm to table butcher",
        "premium meat market",
    ],
    "butcher_local": [
        "specialty butcher shop",
        "independent butcher shop",
        "local butcher shop",
        "neighborhood butcher",
        "favorite butcher shop",
        "family butcher shop",
        "top rated butcher",
        "custom cut butcher",
        "meat market",
        "charcuterie shop",
        "smoked meat shop",
        "old fashioned butcher",
        "halal butcher shop",
        "kosher butcher shop",
        "european butcher shop",
        "italian butcher shop",
        "german butcher shop",
        "deli and butcher",
        "sausage maker shop",
        "meat shop near me",
    ],
    "wine_store_premium": [
        "wine shop",
        "natural wine shop",
        "wine boutique",
        "fine wine store",
        "curated wine shop",
        "sommelier wine shop",
        "rare wine shop",
        "organic wine store",
        "biodynamic wine shop",
        "wine cellar store",
        "premium wine store",
        "artisan wine shop",
        "wine merchant",
        "wine import shop",
        "french wine shop",
        "italian wine shop",
    ],
    "wine_store_local": [
        "wine club membership",
        "favorite wine store",
        "independent wine shop",
        "top rated wine store",
        "neighborhood wine shop",
        "local wine store",
        "wine and cheese shop",
        "best wine store",
        "wine bar and shop",
        "wine tasting shop",
        "hidden gem wine store",
        "boutique wine shop",
        "wine and spirits shop",
        "wine store near me",
        "craft wine shop",
        "family wine shop",
        "wine cellar shop",
        "wine delivery shop",
    ],
    "bakery_premium": [
        "best bakery",
        "artisan bakery",
        "sourdough bakery",
        "french bakery",
        "patisserie",
        "award winning bakery",
        "craft bakery",
        "european bakery",
        "japanese bakery",
        "viennoiserie bakery",
        "wood fired bakery",
        "heritage grain bakery",
        "laminated pastry bakery",
        "best croissant",
        "best bread bakery",
        "pastry chef bakery",
    ],
    "cheese_shop_premium": [
        "best cheese shop",
        "artisan cheese shop",
        "fromagerie",
        "specialty cheese store",
        "cheese monger",
        "imported cheese shop",
        "french cheese shop",
        "cheese cave shop",
        "farmstead cheese shop",
        "award winning cheese shop",
        "gourmet cheese store",
        "craft cheese shop",
        "aged cheese shop",
        "cheese and charcuterie shop",
        "cheese tasting shop",
        "fine cheese shop",
    ],
    "fish_market_premium": [
        "best fish market",
        "fresh seafood market",
        "sustainable seafood market",
        "premium fish market",
        "sushi grade fish market",
        "oyster bar and market",
        "artisan fish market",
        "japanese fish market",
        "dock to table fish market",
        "wild caught fish market",
        "gourmet seafood shop",
        "best seafood counter",
        "fish monger shop",
        "craft seafood market",
        "award winning fish market",
        "whole fish market",
    ],
    "wine_bar_premium": [
        "best wine bar",
        "natural wine bar",
        "wine bar and restaurant",
        "sommelier wine bar",
        "curated wine bar",
        "wine tasting bar",
        "wine flight bar",
        "boutique wine bar",
        "organic wine bar",
        "biodynamic wine bar",
        "wine lounge",
        "wine and small plates",
        "champagne bar",
        "wine bar with food",
        "enoteca",
        "fine wine bar",
    ],
    "deli_premium": [
        "best deli",
        "artisan deli",
        "gourmet deli",
        "jewish deli",
        "italian deli",
        "european deli",
        "old school deli",
        "classic deli",
        "neighborhood deli",
        "famous deli",
        "best sandwich shop",
        "craft sandwich shop",
        "pastrami deli",
        "smoked fish deli",
        "deli and market",
        "specialty deli",
    ],
    "specialty_grocer_premium": [
        "specialty grocery store",
        "gourmet grocery store",
        "artisan grocery",
        "organic grocery store",
        "independent grocery store",
        "specialty food store",
        "gourmet food shop",
        "curated grocery",
        "farm to table grocery",
        "european grocery store",
        "italian grocery store",
        "mediterranean grocery",
        "japanese grocery store",
        "best grocery store",
        "local food market",
        "specialty food market",
    ],
}

# Map search categories to the business_type tag stored on each lead
BUSINESS_TYPE_MAP = {
    "restaurant_destination": "neighbourhood_restaurant",
    "restaurant_neighborhood": "neighbourhood_restaurant",
    "butcher_premium": "butcher",
    "butcher_local": "butcher",
    "wine_store_premium": "wine",
    "wine_store_local": "wine",
    "bakery_premium": "bakery",
    "cheese_shop_premium": "cheese",
    "fish_market_premium": "fish",
    "wine_bar_premium": "wine",
    "deli_premium": "deli",
    "specialty_grocer_premium": "specialty_grocer",
}

# Coarse business_type (4 values) derived from partner_type below.
#   restaurants: destination/neighbourhood/fast_casual
#   wine:        wine bars, wine stores, wineries
#   retail:      butcher, cheese, bakery, fish, deli, specialty_grocer, books, farm
#   other:       anything outside the taxonomy (effectively dropped)
PARTNER_TO_BUSINESS_TYPE: dict[str, str] = {
    "destination_restaurant":   "restaurants",
    "neighbourhood_restaurant": "restaurants",
    "fast_casual":              "restaurants",
    "wine":                     "wine",
    "butcher":                  "retail",
    "cheese":                   "retail",
    "bakery":                   "retail",
    "fish":                     "retail",
    "deli":                     "retail",
    "specialty_grocer":         "retail",
    "books":                    "retail",
    "farm":                     "retail",
}

# Google Maps `type` -> partner_type (fine-grained subvertical).
# None = drop (not a Table22 ICP: big-box grocer, generic bar, non-food retail, etc.)
# Sourced from enumerating distinct `type` values on the 25k-lead backfill.
TYPE_TO_PARTNER_TYPE: dict[str, str | None] = {
    # --- bakery ---
    "Bakery": "bakery",
    "Patisserie": "bakery",
    "Pâtisserie": "bakery",
    "Pastry shop": "bakery",
    "Bagel shop": "bakery",
    "Cake shop": "bakery",
    "Creperie": "bakery",
    "Pie shop": "bakery",
    "Cookie shop": "bakery",
    "Chinese bakery": "bakery",
    "Dessert shop": "bakery",
    "Wholesale bakery": "bakery",

    # --- butcher ---
    "Butcher shop": "butcher",
    "Butcher shop deli": "butcher",
    "Meat products store": "butcher",
    "Meat processor": "butcher",
    "Meat wholesaler": "butcher",

    # --- cheese_shop ---
    "Cheese shop": "cheese",

    # --- deli ---
    "Deli": "deli",
    "Delicatessen": "deli",

    # --- fish_market ---
    "Seafood market": "fish",
    "Fish market": "fish",
    "Seafood store": "fish",
    "Fishmonger": "fish",

    # --- wine_bar ---
    "Wine bar": "wine",

    # --- wine_store (retail + direct-to-consumer producers with subscription potential) ---
    "Wine store": "wine",
    "Wine cellar": "wine",
    "Wine wholesaler and importer": "wine",
    "Winery": "wine",
    "Vineyard": "wine",
    "Wine club": "wine",

    # --- specialty_grocer (curated food retailers; exclude big-box grocery) ---
    "Gourmet grocery store": "specialty_grocer",
    "Specialty food store": "specialty_grocer",
    "Italian grocery store": "specialty_grocer",
    "Asian grocery store": "specialty_grocer",
    "Japanese grocery store": "specialty_grocer",
    "Korean grocery store": "specialty_grocer",
    "Indian grocery store": "specialty_grocer",
    "Mexican grocery store": "specialty_grocer",
    "Organic food store": "specialty_grocer",
    "Natural goods store": "specialty_grocer",
    "Health food store": "specialty_grocer",
    "Produce market": "specialty_grocer",
    "Farm shop": "farm",
    "Spice store": "specialty_grocer",
    "Chocolate shop": "specialty_grocer",
    "Candy store": "specialty_grocer",
    "Pasta shop": "specialty_grocer",

    # --- restaurant (includes bistros, gastropubs, steakhouses, and every cuisine-specific variant) ---
    "Restaurant": "neighbourhood_restaurant",
    "American restaurant": "neighbourhood_restaurant",
    "Italian restaurant": "neighbourhood_restaurant",
    "Seafood restaurant": "neighbourhood_restaurant",
    "Steak house": "destination_restaurant",
    "New American restaurant": "neighbourhood_restaurant",
    "Sandwich shop": "fast_casual",
    "Japanese restaurant": "neighbourhood_restaurant",
    "Sushi restaurant": "neighbourhood_restaurant",
    "Fine dining restaurant": "destination_restaurant",
    "French restaurant": "neighbourhood_restaurant",
    "Mediterranean restaurant": "neighbourhood_restaurant",
    "Mexican restaurant": "neighbourhood_restaurant",
    "Breakfast restaurant": "neighbourhood_restaurant",
    "Barbecue restaurant": "neighbourhood_restaurant",
    "Pizza restaurant": "neighbourhood_restaurant",
    "Brunch restaurant": "neighbourhood_restaurant",
    "Southern restaurant (US)": "neighbourhood_restaurant",
    "Health food restaurant": "neighbourhood_restaurant",
    "Hamburger restaurant": "fast_casual",
    "Bistro": "neighbourhood_restaurant",
    "Spanish restaurant": "neighbourhood_restaurant",
    "Gastropub": "neighbourhood_restaurant",
    "Thai restaurant": "neighbourhood_restaurant",
    "Asian restaurant": "neighbourhood_restaurant",
    "Chinese restaurant": "neighbourhood_restaurant",
    "Californian restaurant": "neighbourhood_restaurant",
    "Diner": "neighbourhood_restaurant",
    "Greek restaurant": "neighbourhood_restaurant",
    "Asian fusion restaurant": "neighbourhood_restaurant",
    "Vegan restaurant": "neighbourhood_restaurant",
    "Oyster bar restaurant": "neighbourhood_restaurant",
    "Fondue restaurant": "neighbourhood_restaurant",
    "Indian restaurant": "neighbourhood_restaurant",
    "Middle Eastern restaurant": "neighbourhood_restaurant",
    "Chicken restaurant": "fast_casual",
    "Latin American restaurant": "neighbourhood_restaurant",
    "Tapas restaurant": "neighbourhood_restaurant",
    "Vietnamese restaurant": "neighbourhood_restaurant",
    "Cajun restaurant": "neighbourhood_restaurant",
    "Brazilian restaurant": "neighbourhood_restaurant",
    "Peruvian restaurant": "neighbourhood_restaurant",
    "Ramen restaurant": "fast_casual",
    "Family restaurant": "neighbourhood_restaurant",
    "Korean restaurant": "neighbourhood_restaurant",
    "German restaurant": "neighbourhood_restaurant",
    "Taco restaurant": "fast_casual",
    "Northern Italian restaurant": "neighbourhood_restaurant",
    "Modern French restaurant": "destination_restaurant",
    "European restaurant": "neighbourhood_restaurant",
    "Cuban restaurant": "neighbourhood_restaurant",
    "Eclectic restaurant": "neighbourhood_restaurant",
    "Lebanese restaurant": "neighbourhood_restaurant",
    "Argentinian restaurant": "neighbourhood_restaurant",
    "Kosher restaurant": "neighbourhood_restaurant",
    "Caribbean restaurant": "neighbourhood_restaurant",
    "Turkish restaurant": "neighbourhood_restaurant",
    "Vegetarian restaurant": "neighbourhood_restaurant",
    "Traditional American restaurant": "neighbourhood_restaurant",
    "Salad shop": "fast_casual",
    "Pacific Northwest restaurant (US)": "neighbourhood_restaurant",
    "Soul food restaurant": "neighbourhood_restaurant",
    "Authentic Japanese restaurant": "neighbourhood_restaurant",
    "Creole restaurant": "neighbourhood_restaurant",
    "Organic restaurant": "neighbourhood_restaurant",
    "Fusion restaurant": "neighbourhood_restaurant",
    "Tex-Mex restaurant": "neighbourhood_restaurant",
    "Dessert restaurant": "neighbourhood_restaurant",
    "Persian restaurant": "neighbourhood_restaurant",
    "Modern European restaurant": "destination_restaurant",
    "Southwestern restaurant (US)": "neighbourhood_restaurant",
    "Lunch restaurant": "neighbourhood_restaurant",
    "Hawaiian restaurant": "neighbourhood_restaurant",
    "Irish restaurant": "neighbourhood_restaurant",
    "Halal restaurant": "neighbourhood_restaurant",
    "Creperie restaurant": "neighbourhood_restaurant",
    "Small plates restaurant": "neighbourhood_restaurant",
    "Modern Indian restaurant": "destination_restaurant",
    "Israeli restaurant": "neighbourhood_restaurant",
    "Eastern European restaurant": "neighbourhood_restaurant",
    "West African restaurant": "neighbourhood_restaurant",
    "Izakaya restaurant": "neighbourhood_restaurant",
    "Cheesesteak restaurant": "fast_casual",
    "Southeast Asian restaurant": "neighbourhood_restaurant",
    "Gluten-free restaurant": "neighbourhood_restaurant",
    "Filipino restaurant": "neighbourhood_restaurant",
    "Georgian restaurant": "neighbourhood_restaurant",
    "Venezuelan restaurant": "neighbourhood_restaurant",
    "Southern Italian restaurant": "neighbourhood_restaurant",
    "Nepalese restaurant": "neighbourhood_restaurant",
    "South American restaurant": "neighbourhood_restaurant",
    "Brasserie": "neighbourhood_restaurant",
    "Ethiopian restaurant": "neighbourhood_restaurant",
    "Native American restaurant": "neighbourhood_restaurant",
    "Pan-Asian restaurant": "neighbourhood_restaurant",
    "Chophouse restaurant": "destination_restaurant",
    "Australian restaurant": "neighbourhood_restaurant",
    "Chicken wings restaurant": "fast_casual",
    "Hot pot restaurant": "neighbourhood_restaurant",
    "British restaurant": "neighbourhood_restaurant",
    "Hot dog restaurant": "fast_casual",
    "Belgian restaurant": "neighbourhood_restaurant",
    "Jewish restaurant": "neighbourhood_restaurant",
    "Austrian restaurant": "neighbourhood_restaurant",
    "Pan-Latin restaurant": "neighbourhood_restaurant",
    "Cambodian restaurant": "neighbourhood_restaurant",
    "Colombian restaurant": "neighbourhood_restaurant",
    "Noodle shop": "fast_casual",
    "Laotian restaurant": "neighbourhood_restaurant",
    "Sicilian restaurant": "neighbourhood_restaurant",
    "Polish restaurant": "neighbourhood_restaurant",
    "Japanese steakhouse": "destination_restaurant",
    "Contemporary Louisiana restaurant": "destination_restaurant",
    "Burmese restaurant": "neighbourhood_restaurant",
    "Pakistani restaurant": "neighbourhood_restaurant",
    "New England restaurant": "neighbourhood_restaurant",
    "Basque restaurant": "neighbourhood_restaurant",
    "Afghan restaurant": "neighbourhood_restaurant",
    "French steakhouse restaurant": "destination_restaurant",
    "Fish & chips restaurant": "fast_casual",
    "Crab house": "neighbourhood_restaurant",
    "Tapas bar": "neighbourhood_restaurant",
    "Poke bar": "fast_casual",
    "Grill": "neighbourhood_restaurant",

    # --- explicit drops (not ICP) ---
    "Grocery store": None,
    "Supermarket": None,
    "Convenience store": None,
    "Department store": None,
    "Shopping mall": None,
    "Discount store": None,
    "Wholesale grocer": None,
    "Grocery delivery service": None,
    "Liquor store": None,
    "State liquor store": None,
    "Beer store": None,
    "Brewery": None,
    "Brewpub": None,
    "Distillery": None,
    "Pub": None,
    "Bar": None,
    "Bar & grill": None,
    "Sports bar": None,
    "Cocktail bar": None,
    "Lounge bar": None,
    "Tiki bar": None,
    "Cider bar": None,
    "Beer garden": None,
    "Beer hall": None,
    "Irish pub": None,
    "Live music bar": None,
    "Coffee shop": None,
    "Cafe": None,
    "Tea house": None,
    "Bubble tea store": None,
    "Juice shop": None,
    "Açaí shop": None,
    "Soft drinks shop": None,
    "Ice cream shop": None,
    "Donut shop": None,
    "Fast food restaurant": None,
    "Takeout Restaurant": None,
    "Hotel": None,
    "Resort hotel": None,
    "Bed & breakfast": None,
    "Event venue": None,
    "Wedding venue": None,
    "Live music venue": None,
    "Night club": None,
    "Jazz club": None,
    "Club": None,
    "Social club": None,
    "Country club": None,
    "Private golf course": None,
    "Farmers' market": None,
    "Food court": None,
    "Market": None,
    "General store": None,
    "Farm": "farm",
    "Dairy farm": "farm",
    "Caterer": None,
    "Mobile caterer": None,
    "Food producer": None,
    "Food and drink": None,
    "Store": None,
    "Book store": "books",
    "Gift shop": None,
    "Clothing store": None,
    "Women's clothing store": None,
    "Boutique": None,
    "Antique store": None,
    "Furniture store": None,
    "Home goods store": None,
    "Kitchen supply store": None,
    "Thrift store": None,
    "Flooring store": None,
    "Garden center": None,
    "Tire shop": None,
    "Outdoor sports store": None,
    "Vitamin & supplements store": None,
    "Drug store": None,
    "Cigar shop": None,
    "Cannabis store": None,
    "Non-profit organization": None,
    "Children's amusement center": None,
    "Tourist attraction": None,
    "Cooking class": None,
    "Painting studio": None,
    "Art gallery": None,
    "Island": None,
    "Asian household goods store": None,

    # --- long-tail additions (from backfill enumeration) ---
    # More bakery variants
    "Cupcake shop": "bakery",
    "Wedding bakery": "bakery",
    # More butcher variants
    "Charcuterie": "butcher",
    "Poultry store": "butcher",
    # More cheese variants
    "Cheese manufacturer": "cheese",
    # More fish variants
    "Fish store": "fish",
    "Fish restaurant": "neighbourhood_restaurant",
    # More specialty grocer variants
    "European grocery store": "specialty_grocer",
    "Fresh food market": "specialty_grocer",
    "Fruit and vegetable store": "specialty_grocer",
    "Nut store": "specialty_grocer",
    "Dairy store": "specialty_grocer",
    "Chocolate cafe": "specialty_grocer",
    "Vegetarian cafe and deli": "deli",
    # Long-tail cuisine restaurants (all map to restaurant)
    "Moroccan restaurant": "neighbourhood_restaurant",
    "Yakiniku restaurant": "neighbourhood_restaurant",
    "Taiwanese restaurant": "neighbourhood_restaurant",
    "Russian restaurant": "neighbourhood_restaurant",
    "African restaurant": "neighbourhood_restaurant",
    "Dumpling restaurant": "neighbourhood_restaurant",
    "Tuscan restaurant": "neighbourhood_restaurant",
    "Buffet restaurant": "neighbourhood_restaurant",
    "Conveyor belt sushi restaurant": "neighbourhood_restaurant",
    "Scandinavian restaurant": "neighbourhood_restaurant",
    "Pacific Rim restaurant": "neighbourhood_restaurant",
    "Pennsylvania Dutch restaurant": "neighbourhood_restaurant",
    "Portuguese restaurant": "neighbourhood_restaurant",
    "Shabu-shabu restaurant": "neighbourhood_restaurant",
    "Uzbeki restaurant": "neighbourhood_restaurant",
    "Egyptian restaurant": "neighbourhood_restaurant",
    "Hungarian restaurant": "neighbourhood_restaurant",
    "Puerto Rican restaurant": "neighbourhood_restaurant",
    "Neapolitan restaurant": "neighbourhood_restaurant",
    "Haute French restaurant": "destination_restaurant",
    "Mid-Atlantic restaurant (US)": "neighbourhood_restaurant",
    "Oaxacan restaurant": "neighbourhood_restaurant",
    "Modern izakaya restaurant": "destination_restaurant",
    "Dim sum restaurant": "neighbourhood_restaurant",
    "East African restaurant": "neighbourhood_restaurant",
    "Haitian restaurant": "neighbourhood_restaurant",
    "Tempura restaurant": "neighbourhood_restaurant",
    "Modern British restaurant": "destination_restaurant",
    "Kaiseki restaurant": "destination_restaurant",
    "Dominican restaurant": "neighbourhood_restaurant",
    "Sri Lankan restaurant": "neighbourhood_restaurant",
    "Swedish restaurant": "neighbourhood_restaurant",
    "Korean barbecue restaurant": "neighbourhood_restaurant",
    "Swiss restaurant": "neighbourhood_restaurant",
    "Burrito restaurant": "fast_casual",
    "Serbian restaurant": "neighbourhood_restaurant",
    "English restaurant": "neighbourhood_restaurant",
    "Falafel restaurant": "fast_casual",
    "Chinese noodle restaurant": "neighbourhood_restaurant",
    "Ecuadorian restaurant": "neighbourhood_restaurant",
    "Armenian restaurant": "neighbourhood_restaurant",
    "Soup restaurant": "fast_casual",
    "Syrian restaurant": "neighbourhood_restaurant",
    "Jamaican restaurant": "neighbourhood_restaurant",
    "Tonkatsu restaurant": "neighbourhood_restaurant",
    "Costa Rican restaurant": "neighbourhood_restaurant",
    "Sichuan restaurant": "neighbourhood_restaurant",
    "Malaysian restaurant": "neighbourhood_restaurant",
    "Continental restaurant": "neighbourhood_restaurant",
    "Polynesian restaurant": "neighbourhood_restaurant",
    "Sukiyaki and Shabu Shabu restaurant": "neighbourhood_restaurant",
    "Chilean restaurant": "neighbourhood_restaurant",
    "Wok restaurant": "neighbourhood_restaurant",
    "Shanghainese restaurant": "neighbourhood_restaurant",
    "Chesapeake restaurant": "neighbourhood_restaurant",
    "Guatemalan restaurant": "neighbourhood_restaurant",
    "Japanese curry restaurant": "neighbourhood_restaurant",
    "Udon noodle restaurant": "neighbourhood_restaurant",
    "Cantonese restaurant": "neighbourhood_restaurant",
    "North Indian restaurant": "neighbourhood_restaurant",
    "Teppanyaki restaurant": "neighbourhood_restaurant",
    "New Zealand restaurant": "neighbourhood_restaurant",
    "Nuevo Latino restaurant": "neighbourhood_restaurant",
    "Yemeni restaurant": "neighbourhood_restaurant",
    "Salvadoran restaurant": "neighbourhood_restaurant",
    "Balinese restaurant": "neighbourhood_restaurant",
    "Floridian restaurant": "neighbourhood_restaurant",
    "Hoagie restaurant": "fast_casual",
    "Chicken shop": "fast_casual",
    "Pan-Asian restaurant": "neighbourhood_restaurant",
    "Pan-Latin restaurant": "neighbourhood_restaurant",
    # Localized names
    "台灣餐廳": "neighbourhood_restaurant",
    "中餐馆": "neighbourhood_restaurant",
    "和食店": "neighbourhood_restaurant",
    "寿司店": "neighbourhood_restaurant",

    # --- long-tail drops ---
    "Art cafe": None,
    "Art center": None,
    "Art supply store": None,
    "Art studio": None,
    "Art gallery": None,
    "Art museum": None,
    "Athletic club": None,
    "Inn": None,
    "Piano bar": None,
    "Gay bar": None,
    "Recreation center": None,
    "Ranch": "farm",
    "Organic farm": "farm",
    "Park": None,
    "State park": None,
    "Dinner theater": None,
    "Notable street": None,
    "Personal chef service": None,
    "Tea store": None,
    "Cash and carry wholesaler": None,
    "Fried chicken takeaway": None,
    "Sushi takeaway": None,
    "Delivery Restaurant": None,
    "Pizza Takeout": None,
    "E-commerce service": None,
    "Game store": None,
    "Espresso bar": None,
    "Coffee roastery": None,
    "Pet store": None,
    "Pet supply store": None,
    "Hardware store": None,
    "Pottery store": None,
    "Tropical fish store": None,
    "Food products supplier": None,
    "Food manufacturer": None,
    "Food and beverage consultant": None,
    "Catering food and drink supplier": None,
    "Botanical garden": None,
    "Restaurant supply store": None,
    "Wine storage facility": None,
    "Wholesaler": None,
    "Wholesale grocer": None,
    "Corporate office": None,
    "Gift basket store": None,
    "Variety store": None,
    "Brewing supply store": None,
    "Manufacturer": None,
    "Greeting card shop": None,
    "Gas station": None,
    "Fish farm": None,
    "Flea market": None,
    "Produce wholesaler": None,
    "Beverage distributor": None,
    "Importer": None,
    "Used book store": "books",
    "Used clothing store": None,
    "Cosmetics store": None,
    "Hair salon": None,
    "Barber shop": None,
    "Florist": None,
    "Cafeteria": None,
    "Banquet hall": None,
    "Business center": None,
    "Transportation service": None,
    "Indoor golf course": None,
    "Golf driving range": None,
    "Amusement center": None,
    "Amusement park": None,
    "Discount supermarket": None,
    "Hypermarket": None,
    "Performing arts theater": None,
    "Fishing pier": None,
    "Foundation": None,
    "Dance hall": None,
    "Festival": None,
    "Sea": None,
    "Mountain peak": None,
    "Observation deck": None,
    "Shoe store": None,
    "Beauty salon": None,
    "Building": None,
    "Historical landmark": None,
    "Aquarium shop": None,
    "Plant nursery": None,
    "Garden": None,
    "Baking supply store": None,
    "Sake brewery": None,
    "Sugar shack": None,
    "Marina": None,
    "Video arcade": None,
    "Traditional teahouse": None,
    "Culinary school": None,
    "Cooking class": None,  # already above but keeping for safety
    "Ford dealer": None,
    "Toyota dealer": None,
    "Mazda dealer": None,
}

# Name-based heuristic rules applied as a second pass. Outputs PARTNER_TYPE values.
# Used for:
#   (1) Salvaging rows classified as dropped/unclassified/no_type.
#   (2) Wine claw-back: override restaurant->wine when name clearly identifies as wine bar.
# Priority: first match wins. Patterns match the lowercased "name + page_title" text.
NAME_HEURISTIC_RULES = [
    # wine wins over restaurant when name/title clearly says wine bar / enoteca
    ("wine",             [r"\bwine bar\b", r"\benoteca\b", r"\bwine lounge\b", r"\bchampagne bar\b",
                          r"\bwine shop\b", r"\bwine store\b", r"\bwine merchant\b",
                          r"\bwine cellar\b", r"\bbottle shop\b"]),
    ("bakery",           [r"\bbakery\b", r"patisserie", r"pâtisserie", r"boulangerie",
                          r"\bbake shop\b", r"\bbagel\b", r"\bcroissant\b", r"\bpastry\b",
                          r"viennoiserie"]),
    ("butcher",          [r"\bbutcher\b", r"\bmeat market\b", r"\bcarniceria\b",
                          r"\bcharcuterie\b", r"\bsausage\b"]),
    ("cheese",           [r"\bcheese shop\b", r"\bfromagerie\b", r"cheese ?monger"]),
    ("fish",             [r"\bfish market\b", r"\bseafood market\b", r"\bfishmonger\b",
                          r"\bfish monger\b"]),
    ("deli",             [r"\bdelicatessen\b"]),
    ("specialty_grocer", [r"\bmercantile\b", r"\bprovisions\b", r"\bemporium\b",
                          r"\bgrocer\b"]),
]

# Comprehensive US cities — all states EXCEPT HI, IN, IA, KS, NV, ND, SD
CITIES = [
    # --- Alabama ---
    "Birmingham, Alabama",
    "Huntsville, Alabama",
    "Mobile, Alabama",
    "Montgomery, Alabama",
    "Tuscaloosa, Alabama",
    "Auburn, Alabama",
    # --- Alaska ---
    "Anchorage, Alaska",
    "Juneau, Alaska",
    "Fairbanks, Alaska",
    # --- Arizona ---
    "Phoenix, Arizona",
    "Scottsdale, Arizona",
    "Tucson, Arizona",
    "Sedona, Arizona",
    "Tempe, Arizona",
    "Mesa, Arizona",
    "Flagstaff, Arizona",
    "Gilbert, Arizona",
    # --- Arkansas ---
    "Little Rock, Arkansas",
    "Fayetteville, Arkansas",
    "Bentonville, Arkansas",
    "Hot Springs, Arkansas",
    "Eureka Springs, Arkansas",
    # --- California (major density) ---
    "Los Angeles, California",
    "San Francisco, California",
    "San Diego, California",
    "Sacramento, California",
    "Oakland, California",
    "Berkeley, California",
    "Pasadena, California",
    "Santa Monica, California",
    "Palo Alto, California",
    "San Jose, California",
    "Irvine, California",
    "Newport Beach, California",
    "La Jolla, California",
    "Santa Barbara, California",
    "Carmel, California",
    "Napa, California",
    "Sonoma, California",
    "Healdsburg, California",
    "St. Helena, California",
    "Mill Valley, California",
    "Walnut Creek, California",
    "Long Beach, California",
    "Burbank, California",
    "Glendale, California",
    "Santa Cruz, California",
    "Monterey, California",
    "San Luis Obispo, California",
    "Fresno, California",
    "Palm Springs, California",
    "Laguna Beach, California",
    "Manhattan Beach, California",
    "Culver City, California",
    "Silver Lake, California",
    "Venice, California",
    "West Hollywood, California",
    "Beverly Hills, California",
    "Riverside, California",
    "Encinitas, California",
    "San Mateo, California",
    "Redwood City, California",
    "Mountain View, California",
    "Davis, California",
    # --- Colorado ---
    "Denver, Colorado",
    "Boulder, Colorado",
    "Fort Collins, Colorado",
    "Colorado Springs, Colorado",
    "Aspen, Colorado",
    "Vail, Colorado",
    "Telluride, Colorado",
    "Durango, Colorado",
    "Littleton, Colorado",
    "Highlands Ranch, Colorado",
    # --- Connecticut ---
    "Stamford, Connecticut",
    "Greenwich, Connecticut",
    "New Haven, Connecticut",
    "Hartford, Connecticut",
    "Westport, Connecticut",
    "West Hartford, Connecticut",
    "Mystic, Connecticut",
    "Fairfield, Connecticut",
    "Darien, Connecticut",
    "Norwalk, Connecticut",
    # --- Delaware ---
    "Wilmington, Delaware",
    "Rehoboth Beach, Delaware",
    "Newark, Delaware",
    # --- Washington DC ---
    "Washington, DC",
    "Georgetown, DC",
    # --- Florida ---
    "Miami, Florida",
    "Tampa, Florida",
    "Orlando, Florida",
    "Jacksonville, Florida",
    "Boca Raton, Florida",
    "Naples, Florida",
    "Sarasota, Florida",
    "West Palm Beach, Florida",
    "Coral Gables, Florida",
    "Delray Beach, Florida",
    "Fort Lauderdale, Florida",
    "St. Petersburg, Florida",
    "Gainesville, Florida",
    "Tallahassee, Florida",
    "Winter Park, Florida",
    "Key West, Florida",
    "Palm Beach, Florida",
    "Coconut Grove, Florida",
    "Miami Beach, Florida",
    "St. Augustine, Florida",
    "Pensacola, Florida",
    "Clearwater, Florida",
    # --- Georgia ---
    "Atlanta, Georgia",
    "Savannah, Georgia",
    "Decatur, Georgia",
    "Marietta, Georgia",
    "Alpharetta, Georgia",
    "Athens, Georgia",
    "Augusta, Georgia",
    "Roswell, Georgia",
    "Sandy Springs, Georgia",
    "Buckhead, Georgia",
    # --- Idaho ---
    "Boise, Idaho",
    "Sun Valley, Idaho",
    "McCall, Idaho",
    "Coeur d'Alene, Idaho",
    "Moscow, Idaho",
    # --- Illinois ---
    "Chicago, Illinois",
    "Evanston, Illinois",
    "Oak Park, Illinois",
    "Naperville, Illinois",
    "Winnetka, Illinois",
    "Lake Forest, Illinois",
    "Hinsdale, Illinois",
    "Springfield, Illinois",
    "Champaign, Illinois",
    "Galena, Illinois",
    # --- Kentucky ---
    "Louisville, Kentucky",
    "Lexington, Kentucky",
    "Covington, Kentucky",
    "Frankfort, Kentucky",
    "Bowling Green, Kentucky",
    # --- Louisiana ---
    "New Orleans, Louisiana",
    "Baton Rouge, Louisiana",
    "Lafayette, Louisiana",
    "Shreveport, Louisiana",
    "Lake Charles, Louisiana",
    # --- Maine ---
    "Portland, Maine",
    "Kennebunkport, Maine",
    "Brunswick, Maine",
    "Camden, Maine",
    "Bar Harbor, Maine",
    "Rockland, Maine",
    # --- Maryland ---
    "Baltimore, Maryland",
    "Bethesda, Maryland",
    "Annapolis, Maryland",
    "Frederick, Maryland",
    "Rockville, Maryland",
    "Columbia, Maryland",
    "Towson, Maryland",
    "Easton, Maryland",
    # --- Massachusetts ---
    "Boston, Massachusetts",
    "Cambridge, Massachusetts",
    "Brookline, Massachusetts",
    "Wellesley, Massachusetts",
    "Newton, Massachusetts",
    "Northampton, Massachusetts",
    "Salem, Massachusetts",
    "Concord, Massachusetts",
    "Somerville, Massachusetts",
    "Worcester, Massachusetts",
    "Lexington, Massachusetts",
    "Nantucket, Massachusetts",
    "Martha's Vineyard, Massachusetts",
    "Provincetown, Massachusetts",
    "Hingham, Massachusetts",
    # --- Michigan ---
    "Detroit, Michigan",
    "Ann Arbor, Michigan",
    "Grand Rapids, Michigan",
    "Traverse City, Michigan",
    "Birmingham, Michigan",
    "Royal Oak, Michigan",
    "Kalamazoo, Michigan",
    "East Lansing, Michigan",
    "Holland, Michigan",
    "Petoskey, Michigan",
    # --- Minnesota ---
    "Minneapolis, Minnesota",
    "St. Paul, Minnesota",
    "Edina, Minnesota",
    "Wayzata, Minnesota",
    "Duluth, Minnesota",
    "Rochester, Minnesota",
    "Excelsior, Minnesota",
    # --- Mississippi ---
    "Jackson, Mississippi",
    "Oxford, Mississippi",
    "Biloxi, Mississippi",
    "Hattiesburg, Mississippi",
    "Greenville, Mississippi",
    # --- Missouri ---
    "St. Louis, Missouri",
    "Kansas City, Missouri",
    "Columbia, Missouri",
    "Springfield, Missouri",
    "Clayton, Missouri",
    "Kirkwood, Missouri",
    # --- Montana ---
    "Bozeman, Montana",
    "Missoula, Montana",
    "Whitefish, Montana",
    "Helena, Montana",
    "Billings, Montana",
    # --- Nebraska ---
    "Omaha, Nebraska",
    "Lincoln, Nebraska",
    # --- New Hampshire ---
    "Portsmouth, New Hampshire",
    "Concord, New Hampshire",
    "Hanover, New Hampshire",
    "Manchester, New Hampshire",
    "Keene, New Hampshire",
    # --- New Jersey ---
    "Hoboken, New Jersey",
    "Jersey City, New Jersey",
    "Montclair, New Jersey",
    "Princeton, New Jersey",
    "Morristown, New Jersey",
    "Red Bank, New Jersey",
    "Westfield, New Jersey",
    "Summit, New Jersey",
    "Ridgewood, New Jersey",
    "Asbury Park, New Jersey",
    "Cape May, New Jersey",
    "Haddonfield, New Jersey",
    # --- New Mexico ---
    "Santa Fe, New Mexico",
    "Albuquerque, New Mexico",
    "Taos, New Mexico",
    "Las Cruces, New Mexico",
    # --- New York (major density) ---
    "New York, New York",
    "Brooklyn, New York",
    "Long Island, New York",
    "White Plains, New York",
    "Westchester, New York",
    "Hudson, New York",
    "Rhinebeck, New York",
    "Sag Harbor, New York",
    "East Hampton, New York",
    "Woodstock, New York",
    "Ithaca, New York",
    "Buffalo, New York",
    "Rochester, New York",
    "Syracuse, New York",
    "Albany, New York",
    "Saratoga Springs, New York",
    "Cold Spring, New York",
    "Beacon, New York",
    "Tarrytown, New York",
    "Nyack, New York",
    "Bronxville, New York",
    "Larchmont, New York",
    "Scarsdale, New York",
    "Great Neck, New York",
    # --- North Carolina ---
    "Charlotte, North Carolina",
    "Raleigh, North Carolina",
    "Asheville, North Carolina",
    "Durham, North Carolina",
    "Wilmington, North Carolina",
    "Chapel Hill, North Carolina",
    "Greensboro, North Carolina",
    "Winston-Salem, North Carolina",
    "Cary, North Carolina",
    "Blowing Rock, North Carolina",
    # --- Ohio ---
    "Columbus, Ohio",
    "Cleveland, Ohio",
    "Cincinnati, Ohio",
    "Akron, Ohio",
    "Dayton, Ohio",
    "Toledo, Ohio",
    "Hudson, Ohio",
    "Chagrin Falls, Ohio",
    "Yellow Springs, Ohio",
    # --- Oklahoma ---
    "Oklahoma City, Oklahoma",
    "Tulsa, Oklahoma",
    "Norman, Oklahoma",
    "Edmond, Oklahoma",
    # --- Oregon ---
    "Portland, Oregon",
    "Bend, Oregon",
    "Eugene, Oregon",
    "Lake Oswego, Oregon",
    "Ashland, Oregon",
    "Hood River, Oregon",
    "Salem, Oregon",
    "Corvallis, Oregon",
    "McMinnville, Oregon",
    # --- Pennsylvania ---
    "Philadelphia, Pennsylvania",
    "Pittsburgh, Pennsylvania",
    "Lancaster, Pennsylvania",
    "Media, Pennsylvania",
    "Wayne, Pennsylvania",
    "Doylestown, Pennsylvania",
    "State College, Pennsylvania",
    "Ardmore, Pennsylvania",
    "Bryn Mawr, Pennsylvania",
    "Swarthmore, Pennsylvania",
    "New Hope, Pennsylvania",
    "Bethlehem, Pennsylvania",
    "Easton, Pennsylvania",
    "West Chester, Pennsylvania",
    # --- Rhode Island ---
    "Providence, Rhode Island",
    "Newport, Rhode Island",
    "Narragansett, Rhode Island",
    # --- South Carolina ---
    "Charleston, South Carolina",
    "Greenville, South Carolina",
    "Columbia, South Carolina",
    "Hilton Head, South Carolina",
    "Beaufort, South Carolina",
    "Bluffton, South Carolina",
    # --- Tennessee ---
    "Nashville, Tennessee",
    "Chattanooga, Tennessee",
    "Knoxville, Tennessee",
    "Memphis, Tennessee",
    "Franklin, Tennessee",
    "Germantown, Tennessee",
    "Johnson City, Tennessee",
    # --- Texas (major density) ---
    "Austin, Texas",
    "Dallas, Texas",
    "Houston, Texas",
    "San Antonio, Texas",
    "Fort Worth, Texas",
    "Plano, Texas",
    "Frisco, Texas",
    "The Woodlands, Texas",
    "El Paso, Texas",
    "Galveston, Texas",
    "Fredericksburg, Texas",
    "Marfa, Texas",
    "College Station, Texas",
    "Southlake, Texas",
    "Highland Park, Texas",
    "University Park, Texas",
    "Dripping Springs, Texas",
    "Round Rock, Texas",
    "Midland, Texas",
    "Lubbock, Texas",
    "McKinney, Texas",
    "Sugar Land, Texas",
    # --- Utah ---
    "Salt Lake City, Utah",
    "Park City, Utah",
    "Provo, Utah",
    "Ogden, Utah",
    "Moab, Utah",
    # --- Vermont ---
    "Burlington, Vermont",
    "Stowe, Vermont",
    "Woodstock, Vermont",
    "Manchester, Vermont",
    "Montpelier, Vermont",
    # --- Virginia ---
    "Richmond, Virginia",
    "Alexandria, Virginia",
    "Arlington, Virginia",
    "Falls Church, Virginia",
    "Fairfax, Virginia",
    "Charlottesville, Virginia",
    "Norfolk, Virginia",
    "Virginia Beach, Virginia",
    "Williamsburg, Virginia",
    "Roanoke, Virginia",
    "Leesburg, Virginia",
    "McLean, Virginia",
    "Tysons, Virginia",
    # --- Washington ---
    "Seattle, Washington",
    "Bellevue, Washington",
    "Kirkland, Washington",
    "Tacoma, Washington",
    "Spokane, Washington",
    "Olympia, Washington",
    "Bellingham, Washington",
    "Bainbridge Island, Washington",
    "Walla Walla, Washington",
    "Woodinville, Washington",
    # --- West Virginia ---
    "Charleston, West Virginia",
    "Morgantown, West Virginia",
    "Lewisburg, West Virginia",
    # --- Wisconsin ---
    "Milwaukee, Wisconsin",
    "Madison, Wisconsin",
    "Door County, Wisconsin",
    "Cedarburg, Wisconsin",
    "Elkhart Lake, Wisconsin",
    "Green Bay, Wisconsin",
    # --- Wyoming ---
    "Jackson, Wyoming",
    "Sheridan, Wyoming",
    "Cody, Wyoming",
    "Laramie, Wyoming",
]

# Keywords for Google Review reservation sentiment analysis
RESERVATION_DIFFICULTY_KEYWORDS = [
    "hard to get a reservation", "hard to get in", "booked weeks out",
    "booked out", "impossible to get", "can't get a table",
    "couldn't get a reservation", "waitlist", "wait list", "fully booked",
    "no availability", "sold out", "book weeks in advance",
    "book months in advance", "good luck getting", "nearly impossible",
]

# Google Reviews config
GOOGLE_REVIEWS_MAX_PER_PLACE = 30  # Cost: ~$0.0006/review

# SHAP-aligned scoring weights (out of 100)
# Partner Type (SHAP #1) is implicit — we tag it during discovery.
# City (SHAP #4) and Google Business Type (SHAP #7) are metadata, not scored.
SCORING_WEIGHTS = {
    "reservation_difficulty": 15,  # SHAP #2 — composite (platform + review sentiment + availability)
    "avg_video_views":         8,  # Re-enabled via IG Reels actor
    "follower_count":         14,  # SHAP #5 — IG followers + FB likes
    "review_count":            5,  # Google review volume
    "press_mentions":         15,  # SHAP #8 — food media coverage
    "awards_count":           12,  # SHAP #11 + #18 — James Beard, Michelin, etc
    "google_rating":           8,  # SHAP #13 — Google rating quality
    "avg_likes":               5,  # Re-enabled via IG Post actor
    "price_tier":              5,  # SHAP #16 — $$$ level
    "has_email_signup":        7,  # bonus — outreach readiness
    "has_ecommerce":           6,  # bonus — fulfillment readiness
}

# Chain keywords to filter out (applies to all business types)
# Chain + liquor keyword blocklists live in `core/keywords.py` so every
# pipeline imports the same lists. Re-exported here for back-compat with
# existing `from config import CHAIN_KEYWORDS, LIQUOR_KEYWORDS` call sites.
from core.keywords import CHAIN_KEYWORDS, LIQUOR_KEYWORDS  # noqa: F401

# Press / food media domains for mention searches
PRESS_DOMAINS = [
    "eater.com", "bonappetit.com", "nytimes.com",
    "foodandwine.com", "saveur.com", "theinfatuation.com",
    "tastingtable.com", "seriouseats.com",
    # Wine-specific press
    "wineenthusiast.com", "winemag.com", "vinepair.com",
    "wine-searcher.com", "decanter.com",
    # Meat/butcher-specific press
    "meatpoultry.com", "meatingplace.com",
]

# Reservation platform priority (higher = harder to get into)
RESERVATION_PLATFORMS = {
    "exploretock.com": 3,   # Tock — typically hardest
    "resy.com": 2,          # Resy
    "opentable.com": 1,     # OpenTable
}
